apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - monitoring/namespace.yaml
  - monitoring/prometheus-config.yaml
  - monitoring/prometheus-deployment.yaml
  - monitoring/prometheus-service.yaml
  - monitoring/grafana-deployment.yaml
  - monitoring/grafana-service.yaml
  - monitoring/grafana-datasources.yaml
  - monitoring/grafana-dashboards-config.yaml
  - monitoring/grafana-dashboard-json.yaml

commonLabels:
  app: notes-app
